---
- hosts: all
  become: yes
  gather_facts: no
  tasks:
   - name: install git, tree, wget on nodes
     apt:
      name: "{{item}}"
      state: present
     with_items:
      - git
      - tree
      - wget    